services:
  opa:
    image: openpolicyagent/opa:latest-debug
    command:
      - run
      - --server
      - --addr=:8181
      - --diagnostic-addr=:8082
      - --log-level=debug

    # healthcheck:
    #   test: wget -qO - http://localhost:8082/health || exit 1
    #   interval: 5s
    #   timeout: 5s
    #   retries: 5

  django:
    build:
      context: .
      dockerfile: ./docker/backend/unittests/django/Dockerfile
    image: secobserve_backend_unittests
    depends_on:
      - opa
    environment:
      # --- Django ---
      DJANGO_DEBUG: "True"
      # --- Admin user ---
      ADMIN_USER: admin
      ADMIN_PASSWORD: admin
      ADMIN_EMAIL: admin@example.com
      # --- Database ---
      DATABASE_ENGINE: django.db.backends.sqlite3
      # --- Security ---
      ALLOWED_HOSTS: localhost
      CORS_ALLOWED_ORIGINS: http://localhost:3000
      DJANGO_SECRET_KEY: NxYPEF5lNGgk3yonndjSbwP77uNJxOvfKTjF5aVBqsHktNlf1wfJHHvJ8iifk32r
      FIELD_ENCRYPTION_KEY: DtlkqVb3wlaVdJK_BU-3mB4wwuuf8xx8YNInajiJ7GU=
      # --- OpenID Connect ---
      OIDC_AUTHORITY: https://authority
      OIDC_CLIENT_ID: client_id
      OIDC_USERNAME: preferred_username
      OIDC_FIRST_NAME: given_name
      OIDC_LAST_NAME: family_name
      OIDC_FULL_NAME: name
      OIDC_EMAIL: email
      OIDC_GROUPS: groups
      # --- OPA ---
      OPA_SERVER_URL: http://opa:8181
    volumes:
      - ./backend:/home
